package profile;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import entities.Organisation;
import featureExtraction.CallFeatureExtraction;

class CallSourceTest {
	private CallProfile profile;

	@BeforeEach
	void setUp() throws Exception {
		profile = new CallProfileImp();
	}
	/**
	 * This test is run on a profile generated by Data1.txt, the same as Transcript 1.
	 */
	@Test
	void testCallSource() {
		
	}

}
